//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _124LTWNC02_QUANLYBANHANGONLINE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbQUANLYBANHANGEntities : DbContext
    {
        public dbQUANLYBANHANGEntities()
            : base("name=dbQUANLYBANHANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPLICATIONS> APPLICATIONS { get; set; }
        public virtual DbSet<GENDER> GENDER { get; set; }
        public virtual DbSet<GENDER_TYPE> GENDER_TYPE { get; set; }
        public virtual DbSet<GROUP_USER> GROUP_USER { get; set; }
        public virtual DbSet<GROUP_USER_RELATIONSHIP_USER> GROUP_USER_RELATIONSHIP_USER { get; set; }
        public virtual DbSet<MENU_FORM> MENU_FORM { get; set; }
        public virtual DbSet<PARTY> PARTY { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbCHITIETHOADON> tbCHITIETHOADON { get; set; }
        public virtual DbSet<tbDANHMUC> tbDANHMUC { get; set; }
        public virtual DbSet<tbHOADON> tbHOADON { get; set; }
        public virtual DbSet<tbKHANHHANG> tbKHANHHANG { get; set; }
        public virtual DbSet<tbSANPHAM> tbSANPHAM { get; set; }
    }
}
